/*
 * Generated by gdbus-codegen 2.30.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include <string.h>

#include "korva-dbus-interface.h"
#include "gdbusinterface.h"
#include "gdbusinterfaceskeleton.h"
#include "gdbusobject.h"
#include "gdbusobjectskeleton.h"
#include "typedefs.h"

#include "korva-marshal.h"

/**
 * g_dbus_gvariant_to_gvalue:
 * @value: A #GVariant.
 * @out_gvalue: Return location pointing to a zero-filled (uninitialized) #GValue.
 *
 * Converts a #GVariant to a #GValue. If @value is floating, it is consumed.
 *
 * The rules specified in the g_dbus_gvalue_to_gvariant() function are
 * used - this function is essentially its reverse form.
 *
 * The conversion never fails - a valid #GValue is always returned in
 * @out_gvalue.
 *
 * Since: 2.30
 */
void
g_dbus_gvariant_to_gvalue (GVariant  *value,
                           GValue    *out_gvalue)
{
  const GVariantType *type;
  gchar **array;

  g_return_if_fail (value != NULL);
  g_return_if_fail (out_gvalue != NULL);

  memset (out_gvalue, '\0', sizeof (GValue));

  switch (g_variant_classify (value))
    {
    case G_VARIANT_CLASS_BOOLEAN:
      g_value_init (out_gvalue, G_TYPE_BOOLEAN);
      g_value_set_boolean (out_gvalue, g_variant_get_boolean (value));
      break;

    case G_VARIANT_CLASS_BYTE:
      g_value_init (out_gvalue, G_TYPE_UCHAR);
      g_value_set_uchar (out_gvalue, g_variant_get_byte (value));
      break;

    case G_VARIANT_CLASS_INT16:
      g_value_init (out_gvalue, G_TYPE_INT);
      g_value_set_int (out_gvalue, g_variant_get_int16 (value));
      break;

    case G_VARIANT_CLASS_UINT16:
      g_value_init (out_gvalue, G_TYPE_UINT);
      g_value_set_uint (out_gvalue, g_variant_get_uint16 (value));
      break;

    case G_VARIANT_CLASS_INT32:
      g_value_init (out_gvalue, G_TYPE_INT);
      g_value_set_int (out_gvalue, g_variant_get_int32 (value));
      break;

    case G_VARIANT_CLASS_UINT32:
      g_value_init (out_gvalue, G_TYPE_UINT);
      g_value_set_uint (out_gvalue, g_variant_get_uint32 (value));
      break;

    case G_VARIANT_CLASS_INT64:
      g_value_init (out_gvalue, G_TYPE_INT64);
      g_value_set_int64 (out_gvalue, g_variant_get_int64 (value));
      break;

    case G_VARIANT_CLASS_UINT64:
      g_value_init (out_gvalue, G_TYPE_UINT64);
      g_value_set_uint64 (out_gvalue, g_variant_get_uint64 (value));
      break;

    case G_VARIANT_CLASS_DOUBLE:
      g_value_init (out_gvalue, G_TYPE_DOUBLE);
      g_value_set_double (out_gvalue, g_variant_get_double (value));
      break;

    case G_VARIANT_CLASS_STRING:
      g_value_init (out_gvalue, G_TYPE_STRING);
      g_value_set_string (out_gvalue, g_variant_get_string (value, NULL));
      break;

    case G_VARIANT_CLASS_OBJECT_PATH:
      g_value_init (out_gvalue, G_TYPE_STRING);
      g_value_set_string (out_gvalue, g_variant_get_string (value, NULL));
      break;

    case G_VARIANT_CLASS_SIGNATURE:
      g_value_init (out_gvalue, G_TYPE_STRING);
      g_value_set_string (out_gvalue, g_variant_get_string (value, NULL));
      break;

    case G_VARIANT_CLASS_ARRAY:
      type = g_variant_get_type (value);
      switch (g_variant_type_peek_string (type)[1])
        {
        case G_VARIANT_CLASS_BYTE:
          g_value_init (out_gvalue, G_TYPE_STRING);
          g_value_set_string (out_gvalue, g_variant_get_bytestring (value));
          break;

        case G_VARIANT_CLASS_STRING:
          g_value_init (out_gvalue, G_TYPE_STRV);
          array = g_variant_dup_strv (value, NULL);
          g_value_take_boxed (out_gvalue, array);
          break;

        case G_VARIANT_CLASS_OBJECT_PATH:
          g_value_init (out_gvalue, G_TYPE_STRV);
          array = g_variant_dup_strv (value, NULL);
          g_value_take_boxed (out_gvalue, array);
          break;

        case G_VARIANT_CLASS_ARRAY:
          switch (g_variant_type_peek_string (type)[2])
            {
            case G_VARIANT_CLASS_BYTE:
              g_value_init (out_gvalue, G_TYPE_STRV);
              array = g_variant_dup_bytestring_array (value, NULL);
              g_value_take_boxed (out_gvalue, array);
              break;

            default:
              g_value_init (out_gvalue, G_TYPE_VARIANT);
              g_value_set_variant (out_gvalue, value);
              break;
            }
          break;

        default:
          g_value_init (out_gvalue, G_TYPE_VARIANT);
          g_value_set_variant (out_gvalue, value);
          break;
        }
      break;

    case G_VARIANT_CLASS_HANDLE:
    case G_VARIANT_CLASS_VARIANT:
    case G_VARIANT_CLASS_MAYBE:
    case G_VARIANT_CLASS_TUPLE:
    case G_VARIANT_CLASS_DICT_ENTRY:
      g_value_init (out_gvalue, G_TYPE_VARIANT);
      g_value_set_variant (out_gvalue, value);
      break;
    }
}


#undef G_OS_UNIX
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.jensge.Korva.Controller1
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:KorvaController1
 * @title: KorvaController1
 * @short_description: Generated C code for the org.jensge.Korva.Controller1 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-jensge-Korva-Controller1.top_of_page">org.jensge.Korva.Controller1</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.jensge.Korva.Controller1 ---- */

static const _ExtendedGDBusArgInfo _korva_controller1_method_info_get_devices_OUT_ARG_Devices =
{
  {
    -1,
    "Devices",
    "aa{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _korva_controller1_method_info_get_devices_OUT_ARG_pointers[] =
{
  &_korva_controller1_method_info_get_devices_OUT_ARG_Devices,
  NULL
};

static const GDBusAnnotationInfo _korva_controller1_method_get_devices_annotation_info_0 =
{
  -1,
  "com.trolltech.QtDBus.QtTypeName.Out0",
  "QVariantMapList",
  NULL
};

static const GDBusAnnotationInfo * const _korva_controller1_method_get_devices_annotation_info_pointers[] =
{
  &_korva_controller1_method_get_devices_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _korva_controller1_method_info_get_devices =
{
  {
    -1,
    "GetDevices",
    NULL,
    (GDBusArgInfo **) &_korva_controller1_method_info_get_devices_OUT_ARG_pointers,
    (GDBusAnnotationInfo **) &_korva_controller1_method_get_devices_annotation_info_pointers
  },
  "handle-get-devices",
  FALSE
};

static const _ExtendedGDBusArgInfo _korva_controller1_method_info_get_device_info_IN_ARG_UID =
{
  {
    -1,
    "UID",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _korva_controller1_method_info_get_device_info_IN_ARG_pointers[] =
{
  &_korva_controller1_method_info_get_device_info_IN_ARG_UID,
  NULL
};

static const _ExtendedGDBusArgInfo _korva_controller1_method_info_get_device_info_OUT_ARG_DeviceInfo =
{
  {
    -1,
    "DeviceInfo",
    "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _korva_controller1_method_info_get_device_info_OUT_ARG_pointers[] =
{
  &_korva_controller1_method_info_get_device_info_OUT_ARG_DeviceInfo,
  NULL
};

static const GDBusAnnotationInfo _korva_controller1_method_get_device_info_annotation_info_0 =
{
  -1,
  "com.trolltech.QtDBus.QtTypeName.Out0",
  "QVariantMap",
  NULL
};

static const GDBusAnnotationInfo * const _korva_controller1_method_get_device_info_annotation_info_pointers[] =
{
  &_korva_controller1_method_get_device_info_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _korva_controller1_method_info_get_device_info =
{
  {
    -1,
    "GetDeviceInfo",
    (GDBusArgInfo **) &_korva_controller1_method_info_get_device_info_IN_ARG_pointers,
    (GDBusArgInfo **) &_korva_controller1_method_info_get_device_info_OUT_ARG_pointers,
    (GDBusAnnotationInfo **) &_korva_controller1_method_get_device_info_annotation_info_pointers
  },
  "handle-get-device-info",
  FALSE
};

static const _ExtendedGDBusArgInfo _korva_controller1_method_info_push_IN_ARG_Source =
{
  {
    -1,
    "Source",
    "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _korva_controller1_method_info_push_IN_ARG_UID =
{
  {
    -1,
    "UID",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _korva_controller1_method_info_push_IN_ARG_pointers[] =
{
  &_korva_controller1_method_info_push_IN_ARG_Source,
  &_korva_controller1_method_info_push_IN_ARG_UID,
  NULL
};

static const _ExtendedGDBusArgInfo _korva_controller1_method_info_push_OUT_ARG_Tag =
{
  {
    -1,
    "Tag",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _korva_controller1_method_info_push_OUT_ARG_pointers[] =
{
  &_korva_controller1_method_info_push_OUT_ARG_Tag,
  NULL
};

static const GDBusAnnotationInfo _korva_controller1_method_push_annotation_info_0 =
{
  -1,
  "com.trolltech.QtDBus.QtTypeName.In0",
  "QVariantMap",
  NULL
};

static const GDBusAnnotationInfo * const _korva_controller1_method_push_annotation_info_pointers[] =
{
  &_korva_controller1_method_push_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _korva_controller1_method_info_push =
{
  {
    -1,
    "Push",
    (GDBusArgInfo **) &_korva_controller1_method_info_push_IN_ARG_pointers,
    (GDBusArgInfo **) &_korva_controller1_method_info_push_OUT_ARG_pointers,
    (GDBusAnnotationInfo **) &_korva_controller1_method_push_annotation_info_pointers
  },
  "handle-push",
  FALSE
};

static const _ExtendedGDBusArgInfo _korva_controller1_method_info_unshare_IN_ARG_Tag =
{
  {
    -1,
    "Tag",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _korva_controller1_method_info_unshare_IN_ARG_pointers[] =
{
  &_korva_controller1_method_info_unshare_IN_ARG_Tag,
  NULL
};

static const _ExtendedGDBusMethodInfo _korva_controller1_method_info_unshare =
{
  {
    -1,
    "Unshare",
    (GDBusArgInfo **) &_korva_controller1_method_info_unshare_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-unshare",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _korva_controller1_method_info_pointers[] =
{
  &_korva_controller1_method_info_get_devices,
  &_korva_controller1_method_info_get_device_info,
  &_korva_controller1_method_info_push,
  &_korva_controller1_method_info_unshare,
  NULL
};

static const _ExtendedGDBusArgInfo _korva_controller1_signal_info_device_available_ARG_Device =
{
  {
    -1,
    "Device",
    "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _korva_controller1_signal_info_device_available_ARG_pointers[] =
{
  &_korva_controller1_signal_info_device_available_ARG_Device,
  NULL
};

static const GDBusAnnotationInfo _korva_controller1_signal_device_available_annotation_info_0 =
{
  -1,
  "com.trolltech.QtDBus.QtTypeName.In0",
  "QVariantMap",
  NULL
};

static const GDBusAnnotationInfo * const _korva_controller1_signal_device_available_annotation_info_pointers[] =
{
  &_korva_controller1_signal_device_available_annotation_info_0,
  NULL
};

static const _ExtendedGDBusSignalInfo _korva_controller1_signal_info_device_available =
{
  {
    -1,
    "DeviceAvailable",
    (GDBusArgInfo **) &_korva_controller1_signal_info_device_available_ARG_pointers,
    (GDBusAnnotationInfo **) &_korva_controller1_signal_device_available_annotation_info_pointers
  },
  "device-available"
};

static const _ExtendedGDBusArgInfo _korva_controller1_signal_info_device_unavailable_ARG_UID =
{
  {
    -1,
    "UID",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _korva_controller1_signal_info_device_unavailable_ARG_pointers[] =
{
  &_korva_controller1_signal_info_device_unavailable_ARG_UID,
  NULL
};

static const _ExtendedGDBusSignalInfo _korva_controller1_signal_info_device_unavailable =
{
  {
    -1,
    "DeviceUnavailable",
    (GDBusArgInfo **) &_korva_controller1_signal_info_device_unavailable_ARG_pointers,
    NULL
  },
  "device-unavailable"
};

static const _ExtendedGDBusSignalInfo * const _korva_controller1_signal_info_pointers[] =
{
  &_korva_controller1_signal_info_device_available,
  &_korva_controller1_signal_info_device_unavailable,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _korva_controller1_interface_info =
{
  {
    -1,
    "org.jensge.Korva.Controller1",
    (GDBusMethodInfo **) &_korva_controller1_method_info_pointers,
    (GDBusSignalInfo **) &_korva_controller1_signal_info_pointers,
    NULL,
    NULL
  },
  "controller1",
};


/**
 * korva_controller1_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-jensge-Korva-Controller1.top_of_page">org.jensge.Korva.Controller1</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
korva_controller1_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_korva_controller1_interface_info;
}

/**
 * korva_controller1_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #KorvaController1 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
korva_controller1_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * KorvaController1:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-jensge-Korva-Controller1.top_of_page">org.jensge.Korva.Controller1</link>.
 */

/**
 * KorvaController1Iface:
 * @parent_iface: The parent interface.
 * @handle_get_device_info: Handler for the #KorvaController1::handle-get-device-info signal.
 * @handle_get_devices: Handler for the #KorvaController1::handle-get-devices signal.
 * @handle_push: Handler for the #KorvaController1::handle-push signal.
 * @handle_unshare: Handler for the #KorvaController1::handle-unshare signal.
 * @device_available: Handler for the #KorvaController1::device-available signal.
 * @device_unavailable: Handler for the #KorvaController1::device-unavailable signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-jensge-Korva-Controller1.top_of_page">org.jensge.Korva.Controller1</link>.
 */

static void
korva_controller1_default_init (KorvaController1Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * KorvaController1::handle-get-devices:
   * @object: A #KorvaController1.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-jensge-Korva-Controller1.GetDevices">GetDevices()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call korva_controller1_complete_get_devices() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-devices",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (KorvaController1Iface, handle_get_devices),
    g_signal_accumulator_true_handled,
    NULL,
    korva_marshal_BOOLEAN__OBJECT,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * KorvaController1::handle-get-device-info:
   * @object: A #KorvaController1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_UID: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-jensge-Korva-Controller1.GetDeviceInfo">GetDeviceInfo()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call korva_controller1_complete_get_device_info() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-device-info",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (KorvaController1Iface, handle_get_device_info),
    g_signal_accumulator_true_handled,
    NULL,
    korva_marshal_BOOLEAN__OBJECT_STRING,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * KorvaController1::handle-push:
   * @object: A #KorvaController1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_Source: Argument passed by remote caller.
   * @arg_UID: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-jensge-Korva-Controller1.Push">Push()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call korva_controller1_complete_push() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-push",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (KorvaController1Iface, handle_push),
    g_signal_accumulator_true_handled,
    NULL,
    korva_marshal_BOOLEAN__OBJECT_VARIANT_STRING,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT, G_TYPE_STRING);

  /**
   * KorvaController1::handle-unshare:
   * @object: A #KorvaController1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_Tag: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-jensge-Korva-Controller1.Unshare">Unshare()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call korva_controller1_complete_unshare() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-unshare",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (KorvaController1Iface, handle_unshare),
    g_signal_accumulator_true_handled,
    NULL,
    korva_marshal_BOOLEAN__OBJECT_STRING,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * KorvaController1::device-available:
   * @object: A #KorvaController1.
   * @arg_Device: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-jensge-Korva-Controller1.DeviceAvailable">"DeviceAvailable"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("device-available",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (KorvaController1Iface, device_available),
    NULL,
    NULL,
    g_cclosure_marshal_VOID__VARIANT,
    G_TYPE_NONE,
    1, G_TYPE_VARIANT);

  /**
   * KorvaController1::device-unavailable:
   * @object: A #KorvaController1.
   * @arg_UID: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-jensge-Korva-Controller1.DeviceUnavailable">"DeviceUnavailable"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("device-unavailable",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (KorvaController1Iface, device_unavailable),
    NULL,
    NULL,
    g_cclosure_marshal_VOID__STRING,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

}

typedef KorvaController1Iface KorvaController1Interface;
G_DEFINE_INTERFACE (KorvaController1, korva_controller1, G_TYPE_OBJECT);

/**
 * korva_controller1_emit_device_available:
 * @object: A #KorvaController1.
 * @arg_Device: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-jensge-Korva-Controller1.DeviceAvailable">"DeviceAvailable"</link> D-Bus signal.
 */
void
korva_controller1_emit_device_available (
    KorvaController1 *object,
    GVariant *arg_Device)
{
  g_signal_emit_by_name (object, "device-available", arg_Device);
}

/**
 * korva_controller1_emit_device_unavailable:
 * @object: A #KorvaController1.
 * @arg_UID: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-jensge-Korva-Controller1.DeviceUnavailable">"DeviceUnavailable"</link> D-Bus signal.
 */
void
korva_controller1_emit_device_unavailable (
    KorvaController1 *object,
    const gchar *arg_UID)
{
  g_signal_emit_by_name (object, "device-unavailable", arg_UID);
}

/**
 * korva_controller1_call_get_devices:
 * @proxy: A #KorvaController1Proxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-jensge-Korva-Controller1.GetDevices">GetDevices()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call korva_controller1_call_get_devices_finish() to get the result of the operation.
 *
 * See korva_controller1_call_get_devices_sync() for the synchronous, blocking version of this method.
 */
void
korva_controller1_call_get_devices (
    KorvaController1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetDevices",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * korva_controller1_call_get_devices_finish:
 * @proxy: A #KorvaController1Proxy.
 * @out_Devices: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to korva_controller1_call_get_devices().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with korva_controller1_call_get_devices().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
korva_controller1_call_get_devices_finish (
    KorvaController1 *proxy,
    GVariant **out_Devices,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aa{sv})",
                 out_Devices);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * korva_controller1_call_get_devices_sync:
 * @proxy: A #KorvaController1Proxy.
 * @out_Devices: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-jensge-Korva-Controller1.GetDevices">GetDevices()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See korva_controller1_call_get_devices() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
korva_controller1_call_get_devices_sync (
    KorvaController1 *proxy,
    GVariant **out_Devices,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetDevices",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@aa{sv})",
                 out_Devices);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * korva_controller1_call_get_device_info:
 * @proxy: A #KorvaController1Proxy.
 * @arg_UID: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-jensge-Korva-Controller1.GetDeviceInfo">GetDeviceInfo()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call korva_controller1_call_get_device_info_finish() to get the result of the operation.
 *
 * See korva_controller1_call_get_device_info_sync() for the synchronous, blocking version of this method.
 */
void
korva_controller1_call_get_device_info (
    KorvaController1 *proxy,
    const gchar *arg_UID,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetDeviceInfo",
    g_variant_new ("(s)",
                   arg_UID),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * korva_controller1_call_get_device_info_finish:
 * @proxy: A #KorvaController1Proxy.
 * @out_DeviceInfo: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to korva_controller1_call_get_device_info().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with korva_controller1_call_get_device_info().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
korva_controller1_call_get_device_info_finish (
    KorvaController1 *proxy,
    GVariant **out_DeviceInfo,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a{sv})",
                 out_DeviceInfo);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * korva_controller1_call_get_device_info_sync:
 * @proxy: A #KorvaController1Proxy.
 * @arg_UID: Argument to pass with the method invocation.
 * @out_DeviceInfo: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-jensge-Korva-Controller1.GetDeviceInfo">GetDeviceInfo()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See korva_controller1_call_get_device_info() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
korva_controller1_call_get_device_info_sync (
    KorvaController1 *proxy,
    const gchar *arg_UID,
    GVariant **out_DeviceInfo,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetDeviceInfo",
    g_variant_new ("(s)",
                   arg_UID),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a{sv})",
                 out_DeviceInfo);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * korva_controller1_call_push:
 * @proxy: A #KorvaController1Proxy.
 * @arg_Source: Argument to pass with the method invocation.
 * @arg_UID: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-jensge-Korva-Controller1.Push">Push()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call korva_controller1_call_push_finish() to get the result of the operation.
 *
 * See korva_controller1_call_push_sync() for the synchronous, blocking version of this method.
 */
void
korva_controller1_call_push (
    KorvaController1 *proxy,
    GVariant *arg_Source,
    const gchar *arg_UID,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Push",
    g_variant_new ("(@a{sv}s)",
                   arg_Source,
                   arg_UID),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * korva_controller1_call_push_finish:
 * @proxy: A #KorvaController1Proxy.
 * @out_Tag: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to korva_controller1_call_push().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with korva_controller1_call_push().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
korva_controller1_call_push_finish (
    KorvaController1 *proxy,
    gchar **out_Tag,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_Tag);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * korva_controller1_call_push_sync:
 * @proxy: A #KorvaController1Proxy.
 * @arg_Source: Argument to pass with the method invocation.
 * @arg_UID: Argument to pass with the method invocation.
 * @out_Tag: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-jensge-Korva-Controller1.Push">Push()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See korva_controller1_call_push() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
korva_controller1_call_push_sync (
    KorvaController1 *proxy,
    GVariant *arg_Source,
    const gchar *arg_UID,
    gchar **out_Tag,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Push",
    g_variant_new ("(@a{sv}s)",
                   arg_Source,
                   arg_UID),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_Tag);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * korva_controller1_call_unshare:
 * @proxy: A #KorvaController1Proxy.
 * @arg_Tag: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-jensge-Korva-Controller1.Unshare">Unshare()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call korva_controller1_call_unshare_finish() to get the result of the operation.
 *
 * See korva_controller1_call_unshare_sync() for the synchronous, blocking version of this method.
 */
void
korva_controller1_call_unshare (
    KorvaController1 *proxy,
    const gchar *arg_Tag,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Unshare",
    g_variant_new ("(s)",
                   arg_Tag),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * korva_controller1_call_unshare_finish:
 * @proxy: A #KorvaController1Proxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to korva_controller1_call_unshare().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with korva_controller1_call_unshare().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
korva_controller1_call_unshare_finish (
    KorvaController1 *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * korva_controller1_call_unshare_sync:
 * @proxy: A #KorvaController1Proxy.
 * @arg_Tag: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-jensge-Korva-Controller1.Unshare">Unshare()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See korva_controller1_call_unshare() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
korva_controller1_call_unshare_sync (
    KorvaController1 *proxy,
    const gchar *arg_Tag,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Unshare",
    g_variant_new ("(s)",
                   arg_Tag),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * korva_controller1_complete_get_devices:
 * @object: A #KorvaController1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @Devices: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-jensge-Korva-Controller1.GetDevices">GetDevices()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
korva_controller1_complete_get_devices (
    KorvaController1 *object,
    GDBusMethodInvocation *invocation,
    GVariant *Devices)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@aa{sv})",
                   Devices));
}

/**
 * korva_controller1_complete_get_device_info:
 * @object: A #KorvaController1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @DeviceInfo: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-jensge-Korva-Controller1.GetDeviceInfo">GetDeviceInfo()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
korva_controller1_complete_get_device_info (
    KorvaController1 *object,
    GDBusMethodInvocation *invocation,
    GVariant *DeviceInfo)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a{sv})",
                   DeviceInfo));
}

/**
 * korva_controller1_complete_push:
 * @object: A #KorvaController1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @Tag: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-jensge-Korva-Controller1.Push">Push()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
korva_controller1_complete_push (
    KorvaController1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *Tag)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   Tag));
}

/**
 * korva_controller1_complete_unshare:
 * @object: A #KorvaController1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-jensge-Korva-Controller1.Unshare">Unshare()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
korva_controller1_complete_unshare (
    KorvaController1 *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * KorvaController1Proxy:
 *
 * The #KorvaController1Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * KorvaController1ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #KorvaController1Proxy.
 */

struct _KorvaController1ProxyPrivate
{
  GData *qdata;
};

static void korva_controller1_proxy_iface_init (KorvaController1Iface *iface);

G_DEFINE_TYPE_WITH_CODE (KorvaController1Proxy, korva_controller1_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (KORVA_TYPE_CONTROLLER1, korva_controller1_proxy_iface_init));

static void
korva_controller1_proxy_finalize (GObject *object)
{
  KorvaController1Proxy *proxy = KORVA_CONTROLLER1_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (korva_controller1_proxy_parent_class)->finalize (object);
}

static void
korva_controller1_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
korva_controller1_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
korva_controller1_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_korva_controller1_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], KORVA_TYPE_CONTROLLER1);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, KORVA_TYPE_CONTROLLER1);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
korva_controller1_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  KorvaController1Proxy *proxy = KORVA_CONTROLLER1_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_korva_controller1_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_korva_controller1_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
korva_controller1_proxy_init (KorvaController1Proxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, KORVA_TYPE_CONTROLLER1_PROXY, KorvaController1ProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), korva_controller1_interface_info ());
}

static void
korva_controller1_proxy_class_init (KorvaController1ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (KorvaController1ProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = korva_controller1_proxy_finalize;
  gobject_class->get_property = korva_controller1_proxy_get_property;
  gobject_class->set_property = korva_controller1_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = korva_controller1_proxy_g_signal;
  proxy_class->g_properties_changed = korva_controller1_proxy_g_properties_changed;

}

static void
korva_controller1_proxy_iface_init (KorvaController1Iface *iface)
{
}

/**
 * korva_controller1_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-jensge-Korva-Controller1.top_of_page">org.jensge.Korva.Controller1</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call korva_controller1_proxy_new_finish() to get the result of the operation.
 *
 * See korva_controller1_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
korva_controller1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (KORVA_TYPE_CONTROLLER1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.jensge.Korva.Controller1", NULL);
}

/**
 * korva_controller1_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to korva_controller1_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with korva_controller1_proxy_new().
 *
 * Returns: (transfer full) (type KorvaController1Proxy): The constructed proxy object or %NULL if @error is set.
 */
KorvaController1 *
korva_controller1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return KORVA_CONTROLLER1 (ret);
  else
    return NULL;
}

/**
 * korva_controller1_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-jensge-Korva-Controller1.top_of_page">org.jensge.Korva.Controller1</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See korva_controller1_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type KorvaController1Proxy): The constructed proxy object or %NULL if @error is set.
 */
KorvaController1 *
korva_controller1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (KORVA_TYPE_CONTROLLER1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.jensge.Korva.Controller1", NULL);
  if (ret != NULL)
    return KORVA_CONTROLLER1 (ret);
  else
    return NULL;
}


/**
 * korva_controller1_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like korva_controller1_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call korva_controller1_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See korva_controller1_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
korva_controller1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (KORVA_TYPE_CONTROLLER1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.jensge.Korva.Controller1", NULL);
}

/**
 * korva_controller1_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to korva_controller1_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with korva_controller1_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type KorvaController1Proxy): The constructed proxy object or %NULL if @error is set.
 */
KorvaController1 *
korva_controller1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return KORVA_CONTROLLER1 (ret);
  else
    return NULL;
}

/**
 * korva_controller1_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like korva_controller1_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See korva_controller1_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type KorvaController1Proxy): The constructed proxy object or %NULL if @error is set.
 */
KorvaController1 *
korva_controller1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (KORVA_TYPE_CONTROLLER1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.jensge.Korva.Controller1", NULL);
  if (ret != NULL)
    return KORVA_CONTROLLER1 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * KorvaController1Skeleton:
 *
 * The #KorvaController1Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * KorvaController1SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #KorvaController1Skeleton.
 */

struct _KorvaController1SkeletonPrivate
{
  GValueArray *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex *lock;
};

/**
 * g_dbus_gvalue_to_gvariant:
 * @gvalue: A #GValue to convert to a #GVariant.
 * @type: A #GVariantType.
 *
 * Converts a #GValue to a #GVariant of the type indicated by the @type parameter.
 *
 * The conversion is using the following rules:
 * <table frame='all'>
 *   <title>#GValue / #GVariant conversion rules</title>
 *   <tgroup cols='2' align='left' colsep='1' rowsep='1'>
 *     <thead>
 *       <row>
 *         <entry>If the #GType for @gvalue is...</entry>
 *         <entry>... then @type must be</entry>
 *       </row>
 *     </thead>
 *     <tbody>
 *       <row>
 *         <entry>#G_TYPE_STRING</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-STRING:CAPS">'s'</link>, <link linkend="G-VARIANT-TYPE-OBJECT-PATH:CAPS">'o'</link>, <link linkend="G-VARIANT-TYPE-SIGNATURE:CAPS">'g'</link> or <link linkend="G-VARIANT-TYPE-BYTESTRING:CAPS">'ay'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_STRV</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-STRING-ARRAY:CAPS">'as'</link>, <link linkend="G-VARIANT-TYPE-OBJECT-PATH-ARRAY:CAPS">'ao'</link> or <link linkend="G-VARIANT-TYPE-BYTESTRING-ARRAY:CAPS">'aay'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_BOOLEAN</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-BOOLEAN:CAPS">'b'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_UCHAR</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-BYTE:CAPS">'y'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_INT</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-INT32:CAPS">'i'</link> or <link linkend="G-VARIANT-TYPE-INT16:CAPS">'n'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_UINT</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-UINT32:CAPS">'u'</link> or <link linkend="G-VARIANT-TYPE-UINT16:CAPS">'q'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_INT64</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-INT64:CAPS">'x'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_UINT64</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-UINT64:CAPS">'t'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_DOUBLE</entry>
 *         <entry><link linkend="G-VARIANT-TYPE-DOUBLE:CAPS">'d'</link></entry>
 *       </row>
 *       <row>
 *         <entry>#G_TYPE_VARIANT</entry>
 *         <entry>Any #GVariantType</entry>
 *       </row>
 *     </tbody>
 *   </tgroup>
 * </table>
 * This can fail if e.g. @gvalue is of type #G_TYPE_STRING and @type
 * is <link linkend="G-VARIANT-TYPE-INT32:CAPS">'i'</link>. It will
 * also fail for any #GType (including e.g. #G_TYPE_OBJECT and
 * #G_TYPE_BOXED derived-types) not in the table above.
 *
 * Note that if @gvalue is of type #G_TYPE_VARIANT and its value is
 * %NULL, the <emphasis>empty</emphasis> #GVariant instance (never
 * %NULL) for @type is returned (e.g. 0 for scalar types, the empty
 * string for string types, <literal>'/'</literal> for object path
 * types, the empty array for any array type and so on).
 *
 * See the g_dbus_gvariant_to_gvalue() function for how to convert a
 * #GVariant to a #GValue.
 *
 * Returns: A #GVariant (never floating) of #GVariantType
 * @type holding the data from @gvalue or %NULL in case of
 * failure. Free with g_variant_unref().
 *
 * Since: 2.30
 */
GVariant *
g_dbus_gvalue_to_gvariant (const GValue       *gvalue,
                           const GVariantType *type)
{
  GVariant *ret;
  const gchar *s;
  const gchar * const *as;
  const gchar *empty_strv[1] = {NULL};

  g_return_val_if_fail (gvalue != NULL, NULL);
  g_return_val_if_fail (type != NULL, NULL);

  ret = NULL;

  /* @type can easily be e.g. "s" with the GValue holding a GVariant - for example this
   * can happen when using the org.gtk.GDBus.C.ForceGVariant annotation with the
   * gdbus-codegen(1) tool.
   */
  if (G_VALUE_TYPE (gvalue) == G_TYPE_VARIANT)
    {
      ret = g_value_dup_variant (gvalue);
    }
  else
    {
      switch (g_variant_type_peek_string (type)[0])
        {
        case G_VARIANT_CLASS_BOOLEAN:
          ret = g_variant_ref_sink (g_variant_new_boolean (g_value_get_boolean (gvalue)));
          break;

        case G_VARIANT_CLASS_BYTE:
          ret = g_variant_ref_sink (g_variant_new_byte (g_value_get_uchar (gvalue)));
          break;

        case G_VARIANT_CLASS_INT16:
          ret = g_variant_ref_sink (g_variant_new_int16 (g_value_get_int (gvalue)));
          break;

        case G_VARIANT_CLASS_UINT16:
          ret = g_variant_ref_sink (g_variant_new_uint16 (g_value_get_uint (gvalue)));
          break;

        case G_VARIANT_CLASS_INT32:
          ret = g_variant_ref_sink (g_variant_new_int32 (g_value_get_int (gvalue)));
          break;

        case G_VARIANT_CLASS_UINT32:
          ret = g_variant_ref_sink (g_variant_new_uint32 (g_value_get_uint (gvalue)));
          break;

        case G_VARIANT_CLASS_INT64:
          ret = g_variant_ref_sink (g_variant_new_int64 (g_value_get_int64 (gvalue)));
          break;

        case G_VARIANT_CLASS_UINT64:
          ret = g_variant_ref_sink (g_variant_new_uint64 (g_value_get_uint64 (gvalue)));
          break;

        case G_VARIANT_CLASS_DOUBLE:
          ret = g_variant_ref_sink (g_variant_new_double (g_value_get_double (gvalue)));
          break;

        case G_VARIANT_CLASS_STRING:
          s = g_value_get_string (gvalue);
          if (s == NULL)
            s = "";
          ret = g_variant_ref_sink (g_variant_new_string (s));
          break;

        case G_VARIANT_CLASS_OBJECT_PATH:
          s = g_value_get_string (gvalue);
          if (s == NULL)
            s = "/";
          ret = g_variant_ref_sink (g_variant_new_object_path (s));
          break;

        case G_VARIANT_CLASS_SIGNATURE:
          s = g_value_get_string (gvalue);
          if (s == NULL)
            s = "";
          ret = g_variant_ref_sink (g_variant_new_signature (s));
          break;

        case G_VARIANT_CLASS_ARRAY:
          switch (g_variant_type_peek_string (type)[1])
            {
            case G_VARIANT_CLASS_BYTE:
              s = g_value_get_string (gvalue);
              if (s == NULL)
                s = "";
              ret = g_variant_ref_sink (g_variant_new_bytestring (s));
              break;

            case G_VARIANT_CLASS_STRING:
              as = g_value_get_boxed (gvalue);
              if (as == NULL)
                as = empty_strv;
              ret = g_variant_ref_sink (g_variant_new_strv (as, -1));
              break;

            case G_VARIANT_CLASS_OBJECT_PATH:
              as = g_value_get_boxed (gvalue);
              if (as == NULL)
                as = empty_strv;
              ret = g_variant_ref_sink (g_variant_new_strv (as, -1));
              break;

            case G_VARIANT_CLASS_ARRAY:
              switch (g_variant_type_peek_string (type)[2])
                {
                case G_VARIANT_CLASS_BYTE:
                  as = g_value_get_boxed (gvalue);
                  if (as == NULL)
                    as = empty_strv;
                  ret = g_variant_ref_sink (g_variant_new_bytestring_array (as, -1));
                  break;

                default:
                  ret = g_value_dup_variant (gvalue);
                  break;
                }
              break;

            default:
              ret = g_value_dup_variant (gvalue);
              break;
            }
          break;

        case G_VARIANT_CLASS_HANDLE:
        case G_VARIANT_CLASS_VARIANT:
        case G_VARIANT_CLASS_MAYBE:
        case G_VARIANT_CLASS_TUPLE:
        case G_VARIANT_CLASS_DICT_ENTRY:
          ret = g_value_dup_variant (gvalue);
          break;
        }
    }

  /* Could be that the GValue is holding a NULL GVariant - in that case,
   * we return an "empty" GVariant instead of a NULL GVariant
   */
  if (ret == NULL)
    {
      GVariant *untrusted_empty;
      untrusted_empty = g_variant_new_from_data (type, NULL, 0, FALSE, NULL, NULL);
      ret = g_variant_ref_sink (g_variant_get_normal_form (untrusted_empty));
      g_variant_unref (untrusted_empty);
    }

  g_assert (!g_variant_is_floating (ret));

  return ret;
}

static void
_korva_controller1_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  KorvaController1Skeleton *skeleton = KORVA_CONTROLLER1_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = {0};
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], KORVA_TYPE_CONTROLLER1);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, KORVA_TYPE_CONTROLLER1);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_korva_controller1_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  KorvaController1Skeleton *skeleton = KORVA_CONTROLLER1_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_korva_controller1_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_korva_controller1_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  KorvaController1Skeleton *skeleton = KORVA_CONTROLLER1_SKELETON (user_data);
  GValue value = {0};
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_korva_controller1_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _korva_controller1_skeleton_vtable =
{
  _korva_controller1_skeleton_handle_method_call,
  _korva_controller1_skeleton_handle_get_property,
  _korva_controller1_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
korva_controller1_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return korva_controller1_interface_info ();
}

static GDBusInterfaceVTable *
korva_controller1_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_korva_controller1_skeleton_vtable;
}

static GVariant *
korva_controller1_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  KorvaController1Skeleton *skeleton = KORVA_CONTROLLER1_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_korva_controller1_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _korva_controller1_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _korva_controller1_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _korva_controller1_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.jensge.Korva.Controller1", info->name, NULL, skeleton);
          if (value != NULL)
            {
              if (g_variant_is_floating (value)) {
                  g_variant_ref_sink (value);
              }
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
korva_controller1_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_korva_controller1_on_signal_device_available (
    KorvaController1 *object,
    GVariant *arg_Device)
{
  KorvaController1Skeleton *skeleton = KORVA_CONTROLLER1_SKELETON (object);
  GDBusConnection *connection = g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton));
  if (connection == NULL)
    return;
  g_dbus_connection_emit_signal (connection,
    NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.jensge.Korva.Controller1", "DeviceAvailable",
    g_variant_new ("(@a{sv})",
                   arg_Device), NULL);
}

static void
_korva_controller1_on_signal_device_unavailable (
    KorvaController1 *object,
    const gchar *arg_UID)
{
  KorvaController1Skeleton *skeleton = KORVA_CONTROLLER1_SKELETON (object);
  GDBusConnection *connection = g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton));
  if (connection == NULL)
    return;
  g_dbus_connection_emit_signal (connection,
    NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.jensge.Korva.Controller1", "DeviceUnavailable",
    g_variant_new ("(s)",
                   arg_UID), NULL);
}

static void korva_controller1_skeleton_iface_init (KorvaController1Iface *iface);
G_DEFINE_TYPE_WITH_CODE (KorvaController1Skeleton, korva_controller1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (KORVA_TYPE_CONTROLLER1, korva_controller1_skeleton_iface_init));

static void
korva_controller1_skeleton_finalize (GObject *object)
{
  KorvaController1Skeleton *skeleton = KORVA_CONTROLLER1_SKELETON (object);
  g_list_foreach (skeleton->priv->changed_properties, (GFunc) _changed_property_free, NULL);
  g_list_free (skeleton->priv->changed_properties);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  if (skeleton->priv->context != NULL)
    g_main_context_unref (skeleton->priv->context);
  g_mutex_free (skeleton->priv->lock);
  G_OBJECT_CLASS (korva_controller1_skeleton_parent_class)->finalize (object);
}

static void
korva_controller1_skeleton_init (KorvaController1Skeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, KORVA_TYPE_CONTROLLER1_SKELETON, KorvaController1SkeletonPrivate);
  skeleton->priv->lock = g_mutex_new ();
  skeleton->priv->context = g_main_context_get_thread_default ();
  if (skeleton->priv->context != NULL)
    g_main_context_ref (skeleton->priv->context);
}

static void
korva_controller1_skeleton_class_init (KorvaController1SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (KorvaController1SkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = korva_controller1_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = korva_controller1_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = korva_controller1_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = korva_controller1_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = korva_controller1_skeleton_dbus_interface_get_vtable;
}

static void
korva_controller1_skeleton_iface_init (KorvaController1Iface *iface)
{
  iface->device_available = _korva_controller1_on_signal_device_available;
  iface->device_unavailable = _korva_controller1_on_signal_device_unavailable;
}

/**
 * korva_controller1_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-jensge-Korva-Controller1.top_of_page">org.jensge.Korva.Controller1</link>.
 *
 * Returns: (transfer full) (type KorvaController1Skeleton): The skeleton object.
 */
KorvaController1 *
korva_controller1_skeleton_new (void)
{
  return KORVA_CONTROLLER1 (g_object_new (KORVA_TYPE_CONTROLLER1_SKELETON, NULL));
}
