/* tui.c generated by valac 0.14.2, the Vala compiler
 * generated from tui.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define TYPE_TRANSFER_UI (transfer_ui_get_type ())
#define TRANSFER_UI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TRANSFER_UI, TransferUi))
#define IS_TRANSFER_UI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TRANSFER_UI))
#define TRANSFER_UI_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_TRANSFER_UI, TransferUiIface))

typedef struct _TransferUi TransferUi;
typedef struct _TransferUiIface TransferUiIface;

#define TYPE_TRANSFER_UI_PROXY (transfer_ui_proxy_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef GDBusProxy TransferUiProxy;
typedef GDBusProxyClass TransferUiProxyClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))

struct _TransferUiIface {
	GTypeInterface parent_iface;
	gchar* (*register_transient_transfer) (TransferUi* self, const gchar* name, gint type, GError** error);
	void (*started) (TransferUi* self, const gchar* id, gdouble progress, GError** error);
	void (*set_values) (TransferUi* self, const gchar* id, GHashTable* key_values, GError** error);
	void (*done) (TransferUi* self, const gchar* id, GError** error);
	void (*cancelled) (TransferUi* self, const gchar* id, GError** error);
};



GType transfer_ui_proxy_get_type (void) G_GNUC_CONST;
guint transfer_ui_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType transfer_ui_get_type (void) G_GNUC_CONST;
gchar* transfer_ui_register_transient_transfer (TransferUi* self, const gchar* name, gint type, GError** error);
void transfer_ui_started (TransferUi* self, const gchar* id, gdouble progress, GError** error);
void transfer_ui_set_values (TransferUi* self, const gchar* id, GHashTable* key_values, GError** error);
void transfer_ui_done (TransferUi* self, const gchar* id, GError** error);
void transfer_ui_cancelled (TransferUi* self, const gchar* id, GError** error);
TransferUi* transfer_ui_create (void);
#define TRANSFER_UI_TRANSFER_TYPE_UPLOAD 0
static void transfer_ui_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static void _dbus_handle_transfer_ui_cancel (TransferUi* self, GVariant* parameters);
static gchar* transfer_ui_proxy_register_transient_transfer (TransferUi* self, const gchar* name, gint type, GError** error);
static void transfer_ui_proxy_started (TransferUi* self, const gchar* id, gdouble progress, GError** error);
static void transfer_ui_proxy_set_values (TransferUi* self, const gchar* id, GHashTable* key_values, GError** error);
static void transfer_ui_proxy_done (TransferUi* self, const gchar* id, GError** error);
static void transfer_ui_proxy_cancelled (TransferUi* self, const gchar* id, GError** error);
static void transfer_ui_proxy_transfer_ui_interface_init (TransferUiIface* iface);
static void _dbus_transfer_ui_register_transient_transfer (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_transfer_ui_started (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_transfer_ui_set_values (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_transfer_ui_done (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void _dbus_transfer_ui_cancelled (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation);
static void transfer_ui_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* transfer_ui_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean transfer_ui_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_transfer_ui_cancel (GObject* _sender, const gchar* id, gpointer* _data);
static void _transfer_ui_unregister_object (gpointer user_data);

static const GDBusArgInfo _transfer_ui_dbus_arg_info_register_transient_transfer_name = {-1, "name", "s"};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_register_transient_transfer_type = {-1, "type", "i"};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_register_transient_transfer_result = {-1, "result", "s"};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_register_transient_transfer_in[] = {&_transfer_ui_dbus_arg_info_register_transient_transfer_name, &_transfer_ui_dbus_arg_info_register_transient_transfer_type, NULL};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_register_transient_transfer_out[] = {&_transfer_ui_dbus_arg_info_register_transient_transfer_result, NULL};
static const GDBusMethodInfo _transfer_ui_dbus_method_info_register_transient_transfer = {-1, "registerTransientTransfer", (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_register_transient_transfer_in), (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_register_transient_transfer_out)};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_started_id = {-1, "id", "s"};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_started_progress = {-1, "progress", "d"};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_started_in[] = {&_transfer_ui_dbus_arg_info_started_id, &_transfer_ui_dbus_arg_info_started_progress, NULL};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_started_out[] = {NULL};
static const GDBusMethodInfo _transfer_ui_dbus_method_info_started = {-1, "started", (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_started_in), (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_started_out)};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_set_values_id = {-1, "id", "s"};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_set_values_key_values = {-1, "key_values", "a{sv}"};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_set_values_in[] = {&_transfer_ui_dbus_arg_info_set_values_id, &_transfer_ui_dbus_arg_info_set_values_key_values, NULL};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_set_values_out[] = {NULL};
static const GDBusMethodInfo _transfer_ui_dbus_method_info_set_values = {-1, "setValues", (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_set_values_in), (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_set_values_out)};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_done_id = {-1, "id", "s"};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_done_in[] = {&_transfer_ui_dbus_arg_info_done_id, NULL};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_done_out[] = {NULL};
static const GDBusMethodInfo _transfer_ui_dbus_method_info_done = {-1, "done", (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_done_in), (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_done_out)};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_cancelled_id = {-1, "id", "s"};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_cancelled_in[] = {&_transfer_ui_dbus_arg_info_cancelled_id, NULL};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_cancelled_out[] = {NULL};
static const GDBusMethodInfo _transfer_ui_dbus_method_info_cancelled = {-1, "cancelled", (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_cancelled_in), (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_cancelled_out)};
static const GDBusMethodInfo * const _transfer_ui_dbus_method_info[] = {&_transfer_ui_dbus_method_info_register_transient_transfer, &_transfer_ui_dbus_method_info_started, &_transfer_ui_dbus_method_info_set_values, &_transfer_ui_dbus_method_info_done, &_transfer_ui_dbus_method_info_cancelled, NULL};
static const GDBusArgInfo _transfer_ui_dbus_arg_info_cancel_id = {-1, "id", "s"};
static const GDBusArgInfo * const _transfer_ui_dbus_arg_info_cancel[] = {&_transfer_ui_dbus_arg_info_cancel_id, NULL};
static const GDBusSignalInfo _transfer_ui_dbus_signal_info_cancel = {-1, "Cancel", (GDBusArgInfo **) (&_transfer_ui_dbus_arg_info_cancel)};
static const GDBusSignalInfo * const _transfer_ui_dbus_signal_info[] = {&_transfer_ui_dbus_signal_info_cancel, NULL};
static const GDBusPropertyInfo * const _transfer_ui_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _transfer_ui_dbus_interface_info = {-1, "com.meego.transferui", (GDBusMethodInfo **) (&_transfer_ui_dbus_method_info), (GDBusSignalInfo **) (&_transfer_ui_dbus_signal_info), (GDBusPropertyInfo **) (&_transfer_ui_dbus_property_info)};
static const GDBusInterfaceVTable _transfer_ui_dbus_interface_vtable = {transfer_ui_dbus_interface_method_call, transfer_ui_dbus_interface_get_property, transfer_ui_dbus_interface_set_property};

gchar* transfer_ui_register_transient_transfer (TransferUi* self, const gchar* name, gint type, GError** error) {
	g_return_val_if_fail (self != NULL, NULL);
	return TRANSFER_UI_GET_INTERFACE (self)->register_transient_transfer (self, name, type, error);
}


void transfer_ui_started (TransferUi* self, const gchar* id, gdouble progress, GError** error) {
	g_return_if_fail (self != NULL);
	TRANSFER_UI_GET_INTERFACE (self)->started (self, id, progress, error);
}


void transfer_ui_set_values (TransferUi* self, const gchar* id, GHashTable* key_values, GError** error) {
	g_return_if_fail (self != NULL);
	TRANSFER_UI_GET_INTERFACE (self)->set_values (self, id, key_values, error);
}


void transfer_ui_done (TransferUi* self, const gchar* id, GError** error) {
	g_return_if_fail (self != NULL);
	TRANSFER_UI_GET_INTERFACE (self)->done (self, id, error);
}


void transfer_ui_cancelled (TransferUi* self, const gchar* id, GError** error) {
	g_return_if_fail (self != NULL);
	TRANSFER_UI_GET_INTERFACE (self)->cancelled (self, id, error);
}


TransferUi* transfer_ui_create (void) {
	TransferUi* result = NULL;
	TransferUi* ui = NULL;
	GError * _inner_error_ = NULL;
	{
		TransferUi* _tmp0_ = NULL;
		TransferUi* _tmp1_;
		_tmp0_ = g_initable_new (TYPE_TRANSFER_UI_PROXY, NULL, &_inner_error_, "g-flags", 0, "g-name", "com.meego.transferui", "g-bus-type", G_BUS_TYPE_SESSION, "g-object-path", "/com/meego/transferui", "g-interface-name", "com.meego.transferui", NULL);
		_tmp1_ = (TransferUi*) _tmp0_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_IO_ERROR) {
				goto __catch0_g_io_error;
			}
			_g_object_unref0 (ui);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_g_object_unref0 (ui);
		ui = _tmp1_;
		result = ui;
		return result;
	}
	goto __finally0;
	__catch0_g_io_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		result = NULL;
		_g_error_free0 (e);
		_g_object_unref0 (ui);
		return result;
	}
	__finally0:
	_g_object_unref0 (ui);
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
	g_clear_error (&_inner_error_);
	return NULL;
}


static void transfer_ui_base_init (TransferUiIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
		g_signal_new ("cancel", TYPE_TRANSFER_UI, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
	}
}


GType transfer_ui_get_type (void) {
	static volatile gsize transfer_ui_type_id__volatile = 0;
	if (g_once_init_enter (&transfer_ui_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TransferUiIface), (GBaseInitFunc) transfer_ui_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType transfer_ui_type_id;
		transfer_ui_type_id = g_type_register_static (G_TYPE_INTERFACE, "TransferUi", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (transfer_ui_type_id, G_TYPE_OBJECT);
		g_type_set_qdata (transfer_ui_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) transfer_ui_proxy_get_type);
		g_type_set_qdata (transfer_ui_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "com.meego.transferui");
		g_type_set_qdata (transfer_ui_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) transfer_ui_register_object);
		g_once_init_leave (&transfer_ui_type_id__volatile, transfer_ui_type_id);
	}
	return transfer_ui_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (TransferUiProxy, transfer_ui_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_TRANSFER_UI, transfer_ui_proxy_transfer_ui_interface_init) )
static void transfer_ui_proxy_class_init (TransferUiProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = transfer_ui_proxy_g_signal;
}


static void _dbus_handle_transfer_ui_cancel (TransferUi* self, GVariant* parameters) {
	GVariantIter _arguments_iter;
	gchar* id = NULL;
	GVariant* _tmp0_;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp0_ = g_variant_iter_next_value (&_arguments_iter);
	id = g_variant_dup_string (_tmp0_, NULL);
	g_variant_unref (_tmp0_);
	g_signal_emit_by_name (self, "cancel", id);
	_g_free0 (id);
}


static void transfer_ui_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
	if (strcmp (signal_name, "Cancel") == 0) {
		_dbus_handle_transfer_ui_cancel ((TransferUi*) proxy, parameters);
	}
}


static void transfer_ui_proxy_init (TransferUiProxy* self) {
}


static gchar* transfer_ui_proxy_register_transient_transfer (TransferUi* self, const gchar* name, gint type, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gchar* _result;
	GVariant* _tmp1_;
	G_IO_ERROR;
	G_DBUS_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.meego.transferui", "registerTransientTransfer");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (name));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (type));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_tmp1_ = g_variant_iter_next_value (&_reply_iter);
	_result = g_variant_dup_string (_tmp1_, NULL);
	g_variant_unref (_tmp1_);
	g_object_unref (_reply_message);
	return _result;
}


static void transfer_ui_proxy_started (TransferUi* self, const gchar* id, gdouble progress, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	G_IO_ERROR;
	G_DBUS_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.meego.transferui", "started");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (id));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_double (progress));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void transfer_ui_proxy_set_values (TransferUi* self, const gchar* id, GHashTable* key_values, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GVariantBuilder _tmp2_;
	GHashTableIter _tmp3_;
	gpointer _tmp4_;
	gpointer _tmp5_;
	GDBusMessage *_reply_message;
	G_IO_ERROR;
	G_DBUS_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.meego.transferui", "setValues");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (id));
	g_hash_table_iter_init (&_tmp3_, key_values);
	g_variant_builder_init (&_tmp2_, G_VARIANT_TYPE ("a{sv}"));
	while (g_hash_table_iter_next (&_tmp3_, &_tmp4_, &_tmp5_)) {
		gchar* _key;
		GVariant* _value;
		_key = (gchar*) _tmp4_;
		_value = (GVariant*) _tmp5_;
		g_variant_builder_add (&_tmp2_, "{?*}", g_variant_new_string (_key), g_variant_new_variant (_value));
	}
	g_variant_builder_add_value (&_arguments_builder, g_variant_builder_end (&_tmp2_));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void transfer_ui_proxy_done (TransferUi* self, const gchar* id, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	G_IO_ERROR;
	G_DBUS_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.meego.transferui", "done");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (id));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void transfer_ui_proxy_cancelled (TransferUi* self, const gchar* id, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	G_IO_ERROR;
	G_DBUS_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "com.meego.transferui", "cancelled");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (id));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return;
	}
	g_object_unref (_reply_message);
}


static void transfer_ui_proxy_transfer_ui_interface_init (TransferUiIface* iface) {
	iface->register_transient_transfer = transfer_ui_proxy_register_transient_transfer;
	iface->started = transfer_ui_proxy_started;
	iface->set_values = transfer_ui_proxy_set_values;
	iface->done = transfer_ui_proxy_done;
	iface->cancelled = transfer_ui_proxy_cancelled;
}


static void _dbus_transfer_ui_register_transient_transfer (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* name = NULL;
	GVariant* _tmp6_;
	gint type = 0;
	GVariant* _tmp7_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gchar* result;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp6_ = g_variant_iter_next_value (&_arguments_iter);
	name = g_variant_dup_string (_tmp6_, NULL);
	g_variant_unref (_tmp6_);
	_tmp7_ = g_variant_iter_next_value (&_arguments_iter);
	type = g_variant_get_int32 (_tmp7_);
	g_variant_unref (_tmp7_);
	result = transfer_ui_register_transient_transfer (self, name, type, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_reply_builder, g_variant_new_string (result));
	_g_free0 (result);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (name);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_transfer_ui_started (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* id = NULL;
	GVariant* _tmp8_;
	gdouble progress = 0.0;
	GVariant* _tmp9_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp8_ = g_variant_iter_next_value (&_arguments_iter);
	id = g_variant_dup_string (_tmp8_, NULL);
	g_variant_unref (_tmp8_);
	_tmp9_ = g_variant_iter_next_value (&_arguments_iter);
	progress = g_variant_get_double (_tmp9_);
	g_variant_unref (_tmp9_);
	transfer_ui_started (self, id, progress, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (id);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_transfer_ui_set_values (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* id = NULL;
	GVariant* _tmp10_;
	GHashTable* key_values = NULL;
	GVariant* _tmp11_;
	GHashTable* _tmp12_;
	GVariantIter _tmp13_;
	GVariant* _tmp14_;
	GVariant* _tmp15_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp10_ = g_variant_iter_next_value (&_arguments_iter);
	id = g_variant_dup_string (_tmp10_, NULL);
	g_variant_unref (_tmp10_);
	_tmp11_ = g_variant_iter_next_value (&_arguments_iter);
	_tmp12_ = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);
	g_variant_iter_init (&_tmp13_, _tmp11_);
	while (g_variant_iter_loop (&_tmp13_, "{?*}", &_tmp14_, &_tmp15_)) {
		g_hash_table_insert (_tmp12_, g_variant_dup_string (_tmp14_, NULL), g_variant_get_variant (_tmp15_));
	}
	key_values = _tmp12_;
	g_variant_unref (_tmp11_);
	transfer_ui_set_values (self, id, key_values, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (id);
	_g_hash_table_unref0 (key_values);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_transfer_ui_done (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* id = NULL;
	GVariant* _tmp16_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp16_ = g_variant_iter_next_value (&_arguments_iter);
	id = g_variant_dup_string (_tmp16_, NULL);
	g_variant_unref (_tmp16_);
	transfer_ui_done (self, id, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (id);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_transfer_ui_cancelled (TransferUi* self, GVariant* parameters, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gchar* id = NULL;
	GVariant* _tmp17_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, parameters);
	_tmp17_ = g_variant_iter_next_value (&_arguments_iter);
	id = g_variant_dup_string (_tmp17_, NULL);
	g_variant_unref (_tmp17_);
	transfer_ui_cancelled (self, id, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	_g_free0 (id);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void transfer_ui_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "registerTransientTransfer") == 0) {
		_dbus_transfer_ui_register_transient_transfer (object, parameters, invocation);
	} else if (strcmp (method_name, "started") == 0) {
		_dbus_transfer_ui_started (object, parameters, invocation);
	} else if (strcmp (method_name, "setValues") == 0) {
		_dbus_transfer_ui_set_values (object, parameters, invocation);
	} else if (strcmp (method_name, "done") == 0) {
		_dbus_transfer_ui_done (object, parameters, invocation);
	} else if (strcmp (method_name, "cancelled") == 0) {
		_dbus_transfer_ui_cancelled (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* transfer_ui_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean transfer_ui_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


static void _dbus_transfer_ui_cancel (GObject* _sender, const gchar* id, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_string (id));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "com.meego.transferui", "Cancel", _arguments, NULL);
}


guint transfer_ui_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_transfer_ui_dbus_interface_info), &_transfer_ui_dbus_interface_vtable, data, _transfer_ui_unregister_object, error);
	if (!result) {
		return 0;
	}
	g_signal_connect (object, "cancel", (GCallback) _dbus_transfer_ui_cancel, data);
	return result;
}


static void _transfer_ui_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_signal_handlers_disconnect_by_func (data[0], _dbus_transfer_ui_cancel, data);
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}



