/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v ../korva/data/Korva.xml -c KorvaController1 org.jensge.Korva.Controller1 -p korva-controller1.h:korva-controller1.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "korva-controller1.h"

/*
 * Implementation of interface class KorvaController1
 */

KorvaController1::KorvaController1(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
    qDBusRegisterMetaType<QList<QVariantMap> > ();
}

KorvaController1::~KorvaController1()
{
}
