#!/bin/sh

set -e
case "$1" in
    configure)
        if dpkg --compare-versions "$2" lt "0.3.0"
        then
            # force reboot only if no or older version. We should have a proper
            # icon otherwise already.
            /usr/lib/package-manager/reboot.sh
        fi
    ;;
esac

exit 0
